include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
    # Enable Dart 3.0+ features
    strict-inference: true

    enable-experiment:
      - inline-class
      - records

linter:
  rules:
  # Add any custom rules here
