// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1818424557;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  U8Array20 crateSha1HasherFinalize({required Sha1Hasher that});

  Sha1Hasher crateSha1HasherNew();

  void crateSha1HasherUpdate({
    required Sha1Hasher that,
    required List<int> data,
  });

  U8Array32 crateSha256HasherFinalize({required Sha256Hasher that});

  Sha256Hasher crateSha256HasherNew();

  void crateSha256HasherUpdate({
    required Sha256Hasher that,
    required List<int> data,
  });

  U8Array32 crateSha256HmacHasherFinalize({required Sha256HmacHasher that});

  Sha256HmacHasher? crateSha256HmacHasherNew({required List<int> key});

  void crateSha256HmacHasherUpdate({
    required Sha256HmacHasher that,
    required List<int> data,
  });

  U8Array64 crateSha512HasherFinalize({required Sha512Hasher that});

  Sha512Hasher crateSha512HasherNew();

  void crateSha512HasherUpdate({
    required Sha512Hasher that,
    required List<int> data,
  });

  Uint8List? crateAes256Decrypt({
    required List<int> ciphertext,
    required List<int> key,
  });

  Future<Uint8List?> crateAes256DecryptAsync({
    required List<int> ciphertext,
    required List<int> key,
  });

  Uint8List? crateAes256Encrypt({
    required List<int> plaintext,
    required List<int> key,
  });

  Future<Uint8List?> crateAes256EncryptAsync({
    required List<int> plaintext,
    required List<int> key,
  });

  (Uint8List, U8Array32)? crateEncryptThenHmac({
    required List<int> plaintext,
    required List<int> encKey,
    required List<int> macKey,
  });

  Future<(Uint8List, U8Array32)?> crateEncryptThenHmacAsync({
    required List<int> plaintext,
    required List<int> encKey,
    required List<int> macKey,
  });

  Uint8List? crateFromHex({required String hexString});

  List<String> crateGetAllAlgorithms();

  BigInt crateHashSize({required String algorithm});

  Uint8List? crateHashThenEncrypt({
    required List<int> data,
    required List<int> key,
  });

  Future<Uint8List?> crateHashThenEncryptAsync({
    required List<int> data,
    required List<int> key,
  });

  U8Array16 crateHmacMd5({required List<int> key, required List<int> data});

  Future<U8Array16> crateHmacMd5Async({
    required List<int> key,
    required List<int> data,
  });

  U8Array20 crateHmacSha1({required List<int> key, required List<int> data});

  Future<U8Array20> crateHmacSha1Async({
    required List<int> key,
    required List<int> data,
  });

  U8Array28 crateHmacSha224({required List<int> key, required List<int> data});

  Future<U8Array28> crateHmacSha224Async({
    required List<int> key,
    required List<int> data,
  });

  U8Array32 crateHmacSha256({required List<int> key, required List<int> data});

  Future<U8Array32> crateHmacSha256Async({
    required List<int> key,
    required List<int> data,
  });

  List<U8Array32> crateHmacSha256Batch({
    required List<int> key,
    required List<Uint8List> messages,
  });

  Future<List<U8Array32>> crateHmacSha256BatchAsync({
    required List<int> key,
    required List<Uint8List> messages,
  });

  U8Array48 crateHmacSha384({required List<int> key, required List<int> data});

  Future<U8Array48> crateHmacSha384Async({
    required List<int> key,
    required List<int> data,
  });

  U8Array64 crateHmacSha512({required List<int> key, required List<int> data});

  Future<U8Array64> crateHmacSha512Async({
    required List<int> key,
    required List<int> data,
  });

  List<U8Array64> crateHmacSha512Batch({
    required List<int> key,
    required List<Uint8List> messages,
  });

  Future<List<U8Array64>> crateHmacSha512BatchAsync({
    required List<int> key,
    required List<Uint8List> messages,
  });

  U8Array16 crateMd5({required List<int> data});

  Future<U8Array16> crateMd5Async({required List<int> data});

  U8Array20 crateSha1({required List<int> data});

  Future<U8Array20> crateSha1Async({required List<int> data});

  U8Array28 crateSha224({required List<int> data});

  Future<U8Array28> crateSha224Async({required List<int> data});

  U8Array32 crateSha256({required List<int> data});

  Future<U8Array32> crateSha256Async({required List<int> data});

  List<U8Array32> crateSha256Batch({required List<Uint8List> inputs});

  Future<List<U8Array32>> crateSha256BatchAsync({
    required List<Uint8List> inputs,
  });

  U8Array48 crateSha384({required List<int> data});

  Future<U8Array48> crateSha384Async({required List<int> data});

  U8Array64 crateSha512({required List<int> data});

  U8Array28 crateSha512224({required List<int> data});

  Future<U8Array28> crateSha512224Async({required List<int> data});

  U8Array32 crateSha512256({required List<int> data});

  Future<U8Array32> crateSha512256Async({required List<int> data});

  Future<U8Array64> crateSha512Async({required List<int> data});

  List<U8Array64> crateSha512Batch({required List<Uint8List> inputs});

  Future<List<U8Array64>> crateSha512BatchAsync({
    required List<Uint8List> inputs,
  });

  String crateToHex({required List<int> bytes});

  Uint8List? crateVerifyHmacThenDecrypt({
    required List<int> ciphertext,
    required List<int> mac,
    required List<int> encKey,
    required List<int> macKey,
  });

  Future<Uint8List?> crateVerifyHmacThenDecryptAsync({
    required List<int> ciphertext,
    required List<int> mac,
    required List<int> encKey,
    required List<int> macKey,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Sha1Hasher;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Sha1Hasher;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_Sha1HasherPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Sha256Hasher;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Sha256Hasher;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_Sha256HasherPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Sha256HmacHasher;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Sha256HmacHasher;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_Sha256HmacHasherPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Sha512Hasher;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Sha512Hasher;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_Sha512HasherPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  U8Array20 crateSha1HasherFinalize({required Sha1Hasher that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha1Hasher(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_20,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha1HasherFinalizeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha1HasherFinalizeConstMeta =>
      const TaskConstMeta(debugName: "Sha1Hasher_finalize", argNames: ["that"]);

  @override
  Sha1Hasher crateSha1HasherNew() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha1Hasher,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha1HasherNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha1HasherNewConstMeta =>
      const TaskConstMeta(debugName: "Sha1Hasher_new", argNames: []);

  @override
  void crateSha1HasherUpdate({
    required Sha1Hasher that,
    required List<int> data,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha1Hasher(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha1HasherUpdateConstMeta,
        argValues: [that, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha1HasherUpdateConstMeta => const TaskConstMeta(
    debugName: "Sha1Hasher_update",
    argNames: ["that", "data"],
  );

  @override
  U8Array32 crateSha256HasherFinalize({required Sha256Hasher that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256Hasher(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha256HasherFinalizeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha256HasherFinalizeConstMeta => const TaskConstMeta(
    debugName: "Sha256Hasher_finalize",
    argNames: ["that"],
  );

  @override
  Sha256Hasher crateSha256HasherNew() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256Hasher,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha256HasherNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha256HasherNewConstMeta =>
      const TaskConstMeta(debugName: "Sha256Hasher_new", argNames: []);

  @override
  void crateSha256HasherUpdate({
    required Sha256Hasher that,
    required List<int> data,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256Hasher(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha256HasherUpdateConstMeta,
        argValues: [that, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha256HasherUpdateConstMeta => const TaskConstMeta(
    debugName: "Sha256Hasher_update",
    argNames: ["that", "data"],
  );

  @override
  U8Array32 crateSha256HmacHasherFinalize({required Sha256HmacHasher that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256HmacHasher(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha256HmacHasherFinalizeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha256HmacHasherFinalizeConstMeta =>
      const TaskConstMeta(
        debugName: "Sha256HmacHasher_finalize",
        argNames: ["that"],
      );

  @override
  Sha256HmacHasher? crateSha256HmacHasherNew({required List<int> key}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256HmacHasher,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha256HmacHasherNewConstMeta,
        argValues: [key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha256HmacHasherNewConstMeta =>
      const TaskConstMeta(debugName: "Sha256HmacHasher_new", argNames: ["key"]);

  @override
  void crateSha256HmacHasherUpdate({
    required Sha256HmacHasher that,
    required List<int> data,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256HmacHasher(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha256HmacHasherUpdateConstMeta,
        argValues: [that, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha256HmacHasherUpdateConstMeta =>
      const TaskConstMeta(
        debugName: "Sha256HmacHasher_update",
        argNames: ["that", "data"],
      );

  @override
  U8Array64 crateSha512HasherFinalize({required Sha512Hasher that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha512Hasher(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha512HasherFinalizeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha512HasherFinalizeConstMeta => const TaskConstMeta(
    debugName: "Sha512Hasher_finalize",
    argNames: ["that"],
  );

  @override
  Sha512Hasher crateSha512HasherNew() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha512Hasher,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha512HasherNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha512HasherNewConstMeta =>
      const TaskConstMeta(debugName: "Sha512Hasher_new", argNames: []);

  @override
  void crateSha512HasherUpdate({
    required Sha512Hasher that,
    required List<int> data,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha512Hasher(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha512HasherUpdateConstMeta,
        argValues: [that, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha512HasherUpdateConstMeta => const TaskConstMeta(
    debugName: "Sha512Hasher_update",
    argNames: ["that", "data"],
  );

  @override
  Uint8List? crateAes256Decrypt({
    required List<int> ciphertext,
    required List<int> key,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(ciphertext, serializer);
          sse_encode_list_prim_u_8_loose(key, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateAes256DecryptConstMeta,
        argValues: [ciphertext, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAes256DecryptConstMeta => const TaskConstMeta(
    debugName: "aes256_decrypt",
    argNames: ["ciphertext", "key"],
  );

  @override
  Future<Uint8List?> crateAes256DecryptAsync({
    required List<int> ciphertext,
    required List<int> key,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(ciphertext, serializer);
          sse_encode_list_prim_u_8_loose(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateAes256DecryptAsyncConstMeta,
        argValues: [ciphertext, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAes256DecryptAsyncConstMeta => const TaskConstMeta(
    debugName: "aes256_decrypt_async",
    argNames: ["ciphertext", "key"],
  );

  @override
  Uint8List? crateAes256Encrypt({
    required List<int> plaintext,
    required List<int> key,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(plaintext, serializer);
          sse_encode_list_prim_u_8_loose(key, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateAes256EncryptConstMeta,
        argValues: [plaintext, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAes256EncryptConstMeta => const TaskConstMeta(
    debugName: "aes256_encrypt",
    argNames: ["plaintext", "key"],
  );

  @override
  Future<Uint8List?> crateAes256EncryptAsync({
    required List<int> plaintext,
    required List<int> key,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(plaintext, serializer);
          sse_encode_list_prim_u_8_loose(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateAes256EncryptAsyncConstMeta,
        argValues: [plaintext, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAes256EncryptAsyncConstMeta => const TaskConstMeta(
    debugName: "aes256_encrypt_async",
    argNames: ["plaintext", "key"],
  );

  @override
  (Uint8List, U8Array32)? crateEncryptThenHmac({
    required List<int> plaintext,
    required List<int> encKey,
    required List<int> macKey,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(plaintext, serializer);
          sse_encode_list_prim_u_8_loose(encKey, serializer);
          sse_encode_list_prim_u_8_loose(macKey, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_opt_box_autoadd_record_list_prim_u_8_strict_u_8_array_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateEncryptThenHmacConstMeta,
        argValues: [plaintext, encKey, macKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateEncryptThenHmacConstMeta => const TaskConstMeta(
    debugName: "encrypt_then_hmac",
    argNames: ["plaintext", "encKey", "macKey"],
  );

  @override
  Future<(Uint8List, U8Array32)?> crateEncryptThenHmacAsync({
    required List<int> plaintext,
    required List<int> encKey,
    required List<int> macKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(plaintext, serializer);
          sse_encode_list_prim_u_8_loose(encKey, serializer);
          sse_encode_list_prim_u_8_loose(macKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_opt_box_autoadd_record_list_prim_u_8_strict_u_8_array_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateEncryptThenHmacAsyncConstMeta,
        argValues: [plaintext, encKey, macKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateEncryptThenHmacAsyncConstMeta => const TaskConstMeta(
    debugName: "encrypt_then_hmac_async",
    argNames: ["plaintext", "encKey", "macKey"],
  );

  @override
  Uint8List? crateFromHex({required String hexString}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hexString, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateFromHexConstMeta,
        argValues: [hexString],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFromHexConstMeta =>
      const TaskConstMeta(debugName: "from_hex", argNames: ["hexString"]);

  @override
  List<String> crateGetAllAlgorithms() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateGetAllAlgorithmsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGetAllAlgorithmsConstMeta =>
      const TaskConstMeta(debugName: "get_all_algorithms", argNames: []);

  @override
  BigInt crateHashSize({required String algorithm}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(algorithm, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: null,
        ),
        constMeta: kCrateHashSizeConstMeta,
        argValues: [algorithm],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHashSizeConstMeta =>
      const TaskConstMeta(debugName: "hash_size", argNames: ["algorithm"]);

  @override
  Uint8List? crateHashThenEncrypt({
    required List<int> data,
    required List<int> key,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          sse_encode_list_prim_u_8_loose(key, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateHashThenEncryptConstMeta,
        argValues: [data, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHashThenEncryptConstMeta => const TaskConstMeta(
    debugName: "hash_then_encrypt",
    argNames: ["data", "key"],
  );

  @override
  Future<Uint8List?> crateHashThenEncryptAsync({
    required List<int> data,
    required List<int> key,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          sse_encode_list_prim_u_8_loose(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateHashThenEncryptAsyncConstMeta,
        argValues: [data, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHashThenEncryptAsyncConstMeta => const TaskConstMeta(
    debugName: "hash_then_encrypt_async",
    argNames: ["data", "key"],
  );

  @override
  U8Array16 crateHmacMd5({required List<int> key, required List<int> data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_16,
          decodeErrorData: null,
        ),
        constMeta: kCrateHmacMd5ConstMeta,
        argValues: [key, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHmacMd5ConstMeta =>
      const TaskConstMeta(debugName: "hmac_md5", argNames: ["key", "data"]);

  @override
  Future<U8Array16> crateHmacMd5Async({
    required List<int> key,
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_16,
          decodeErrorData: null,
        ),
        constMeta: kCrateHmacMd5AsyncConstMeta,
        argValues: [key, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHmacMd5AsyncConstMeta => const TaskConstMeta(
    debugName: "hmac_md5_async",
    argNames: ["key", "data"],
  );

  @override
  U8Array20 crateHmacSha1({required List<int> key, required List<int> data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_20,
          decodeErrorData: null,
        ),
        constMeta: kCrateHmacSha1ConstMeta,
        argValues: [key, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHmacSha1ConstMeta =>
      const TaskConstMeta(debugName: "hmac_sha1", argNames: ["key", "data"]);

  @override
  Future<U8Array20> crateHmacSha1Async({
    required List<int> key,
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_20,
          decodeErrorData: null,
        ),
        constMeta: kCrateHmacSha1AsyncConstMeta,
        argValues: [key, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHmacSha1AsyncConstMeta => const TaskConstMeta(
    debugName: "hmac_sha1_async",
    argNames: ["key", "data"],
  );

  @override
  U8Array28 crateHmacSha224({required List<int> key, required List<int> data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_28,
          decodeErrorData: null,
        ),
        constMeta: kCrateHmacSha224ConstMeta,
        argValues: [key, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHmacSha224ConstMeta =>
      const TaskConstMeta(debugName: "hmac_sha224", argNames: ["key", "data"]);

  @override
  Future<U8Array28> crateHmacSha224Async({
    required List<int> key,
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_28,
          decodeErrorData: null,
        ),
        constMeta: kCrateHmacSha224AsyncConstMeta,
        argValues: [key, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHmacSha224AsyncConstMeta => const TaskConstMeta(
    debugName: "hmac_sha224_async",
    argNames: ["key", "data"],
  );

  @override
  U8Array32 crateHmacSha256({required List<int> key, required List<int> data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateHmacSha256ConstMeta,
        argValues: [key, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHmacSha256ConstMeta =>
      const TaskConstMeta(debugName: "hmac_sha256", argNames: ["key", "data"]);

  @override
  Future<U8Array32> crateHmacSha256Async({
    required List<int> key,
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateHmacSha256AsyncConstMeta,
        argValues: [key, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHmacSha256AsyncConstMeta => const TaskConstMeta(
    debugName: "hmac_sha256_async",
    argNames: ["key", "data"],
  );

  @override
  List<U8Array32> crateHmacSha256Batch({
    required List<int> key,
    required List<Uint8List> messages,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_list_prim_u_8_strict(messages, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 32)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_u_8_array_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateHmacSha256BatchConstMeta,
        argValues: [key, messages],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHmacSha256BatchConstMeta => const TaskConstMeta(
    debugName: "hmac_sha256_batch",
    argNames: ["key", "messages"],
  );

  @override
  Future<List<U8Array32>> crateHmacSha256BatchAsync({
    required List<int> key,
    required List<Uint8List> messages,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_list_prim_u_8_strict(messages, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_u_8_array_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateHmacSha256BatchAsyncConstMeta,
        argValues: [key, messages],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHmacSha256BatchAsyncConstMeta => const TaskConstMeta(
    debugName: "hmac_sha256_batch_async",
    argNames: ["key", "messages"],
  );

  @override
  U8Array48 crateHmacSha384({required List<int> key, required List<int> data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 34)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_48,
          decodeErrorData: null,
        ),
        constMeta: kCrateHmacSha384ConstMeta,
        argValues: [key, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHmacSha384ConstMeta =>
      const TaskConstMeta(debugName: "hmac_sha384", argNames: ["key", "data"]);

  @override
  Future<U8Array48> crateHmacSha384Async({
    required List<int> key,
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_48,
          decodeErrorData: null,
        ),
        constMeta: kCrateHmacSha384AsyncConstMeta,
        argValues: [key, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHmacSha384AsyncConstMeta => const TaskConstMeta(
    debugName: "hmac_sha384_async",
    argNames: ["key", "data"],
  );

  @override
  U8Array64 crateHmacSha512({required List<int> key, required List<int> data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 36)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateHmacSha512ConstMeta,
        argValues: [key, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHmacSha512ConstMeta =>
      const TaskConstMeta(debugName: "hmac_sha512", argNames: ["key", "data"]);

  @override
  Future<U8Array64> crateHmacSha512Async({
    required List<int> key,
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 37,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateHmacSha512AsyncConstMeta,
        argValues: [key, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHmacSha512AsyncConstMeta => const TaskConstMeta(
    debugName: "hmac_sha512_async",
    argNames: ["key", "data"],
  );

  @override
  List<U8Array64> crateHmacSha512Batch({
    required List<int> key,
    required List<Uint8List> messages,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_list_prim_u_8_strict(messages, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 38)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_u_8_array_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateHmacSha512BatchConstMeta,
        argValues: [key, messages],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHmacSha512BatchConstMeta => const TaskConstMeta(
    debugName: "hmac_sha512_batch",
    argNames: ["key", "messages"],
  );

  @override
  Future<List<U8Array64>> crateHmacSha512BatchAsync({
    required List<int> key,
    required List<Uint8List> messages,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_list_prim_u_8_strict(messages, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 39,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_u_8_array_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateHmacSha512BatchAsyncConstMeta,
        argValues: [key, messages],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHmacSha512BatchAsyncConstMeta => const TaskConstMeta(
    debugName: "hmac_sha512_batch_async",
    argNames: ["key", "messages"],
  );

  @override
  U8Array16 crateMd5({required List<int> data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 40)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_16,
          decodeErrorData: null,
        ),
        constMeta: kCrateMd5ConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateMd5ConstMeta =>
      const TaskConstMeta(debugName: "md5", argNames: ["data"]);

  @override
  Future<U8Array16> crateMd5Async({required List<int> data}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 41,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_16,
          decodeErrorData: null,
        ),
        constMeta: kCrateMd5AsyncConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateMd5AsyncConstMeta =>
      const TaskConstMeta(debugName: "md5_async", argNames: ["data"]);

  @override
  U8Array20 crateSha1({required List<int> data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 42)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_20,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha1ConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha1ConstMeta =>
      const TaskConstMeta(debugName: "sha1", argNames: ["data"]);

  @override
  Future<U8Array20> crateSha1Async({required List<int> data}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 43,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_20,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha1AsyncConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha1AsyncConstMeta =>
      const TaskConstMeta(debugName: "sha1_async", argNames: ["data"]);

  @override
  U8Array28 crateSha224({required List<int> data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 44)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_28,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha224ConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha224ConstMeta =>
      const TaskConstMeta(debugName: "sha224", argNames: ["data"]);

  @override
  Future<U8Array28> crateSha224Async({required List<int> data}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 45,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_28,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha224AsyncConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha224AsyncConstMeta =>
      const TaskConstMeta(debugName: "sha224_async", argNames: ["data"]);

  @override
  U8Array32 crateSha256({required List<int> data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 46)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha256ConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha256ConstMeta =>
      const TaskConstMeta(debugName: "sha256", argNames: ["data"]);

  @override
  Future<U8Array32> crateSha256Async({required List<int> data}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 47,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha256AsyncConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha256AsyncConstMeta =>
      const TaskConstMeta(debugName: "sha256_async", argNames: ["data"]);

  @override
  List<U8Array32> crateSha256Batch({required List<Uint8List> inputs}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_list_prim_u_8_strict(inputs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 48)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_u_8_array_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha256BatchConstMeta,
        argValues: [inputs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha256BatchConstMeta =>
      const TaskConstMeta(debugName: "sha256_batch", argNames: ["inputs"]);

  @override
  Future<List<U8Array32>> crateSha256BatchAsync({
    required List<Uint8List> inputs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_list_prim_u_8_strict(inputs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 49,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_u_8_array_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha256BatchAsyncConstMeta,
        argValues: [inputs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha256BatchAsyncConstMeta => const TaskConstMeta(
    debugName: "sha256_batch_async",
    argNames: ["inputs"],
  );

  @override
  U8Array48 crateSha384({required List<int> data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 50)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_48,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha384ConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha384ConstMeta =>
      const TaskConstMeta(debugName: "sha384", argNames: ["data"]);

  @override
  Future<U8Array48> crateSha384Async({required List<int> data}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 51,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_48,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha384AsyncConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha384AsyncConstMeta =>
      const TaskConstMeta(debugName: "sha384_async", argNames: ["data"]);

  @override
  U8Array64 crateSha512({required List<int> data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 52)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha512ConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha512ConstMeta =>
      const TaskConstMeta(debugName: "sha512", argNames: ["data"]);

  @override
  U8Array28 crateSha512224({required List<int> data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 53)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_28,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha512224ConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha512224ConstMeta =>
      const TaskConstMeta(debugName: "sha512_224", argNames: ["data"]);

  @override
  Future<U8Array28> crateSha512224Async({required List<int> data}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 54,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_28,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha512224AsyncConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha512224AsyncConstMeta =>
      const TaskConstMeta(debugName: "sha512_224_async", argNames: ["data"]);

  @override
  U8Array32 crateSha512256({required List<int> data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 55)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha512256ConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha512256ConstMeta =>
      const TaskConstMeta(debugName: "sha512_256", argNames: ["data"]);

  @override
  Future<U8Array32> crateSha512256Async({required List<int> data}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 56,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha512256AsyncConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha512256AsyncConstMeta =>
      const TaskConstMeta(debugName: "sha512_256_async", argNames: ["data"]);

  @override
  Future<U8Array64> crateSha512Async({required List<int> data}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 57,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha512AsyncConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha512AsyncConstMeta =>
      const TaskConstMeta(debugName: "sha512_async", argNames: ["data"]);

  @override
  List<U8Array64> crateSha512Batch({required List<Uint8List> inputs}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_list_prim_u_8_strict(inputs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 58)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_u_8_array_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha512BatchConstMeta,
        argValues: [inputs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha512BatchConstMeta =>
      const TaskConstMeta(debugName: "sha512_batch", argNames: ["inputs"]);

  @override
  Future<List<U8Array64>> crateSha512BatchAsync({
    required List<Uint8List> inputs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_list_prim_u_8_strict(inputs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 59,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_u_8_array_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha512BatchAsyncConstMeta,
        argValues: [inputs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha512BatchAsyncConstMeta => const TaskConstMeta(
    debugName: "sha512_batch_async",
    argNames: ["inputs"],
  );

  @override
  String crateToHex({required List<int> bytes}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 60)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateToHexConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateToHexConstMeta =>
      const TaskConstMeta(debugName: "to_hex", argNames: ["bytes"]);

  @override
  Uint8List? crateVerifyHmacThenDecrypt({
    required List<int> ciphertext,
    required List<int> mac,
    required List<int> encKey,
    required List<int> macKey,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(ciphertext, serializer);
          sse_encode_list_prim_u_8_loose(mac, serializer);
          sse_encode_list_prim_u_8_loose(encKey, serializer);
          sse_encode_list_prim_u_8_loose(macKey, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 61)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateVerifyHmacThenDecryptConstMeta,
        argValues: [ciphertext, mac, encKey, macKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateVerifyHmacThenDecryptConstMeta => const TaskConstMeta(
    debugName: "verify_hmac_then_decrypt",
    argNames: ["ciphertext", "mac", "encKey", "macKey"],
  );

  @override
  Future<Uint8List?> crateVerifyHmacThenDecryptAsync({
    required List<int> ciphertext,
    required List<int> mac,
    required List<int> encKey,
    required List<int> macKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(ciphertext, serializer);
          sse_encode_list_prim_u_8_loose(mac, serializer);
          sse_encode_list_prim_u_8_loose(encKey, serializer);
          sse_encode_list_prim_u_8_loose(macKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 62,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateVerifyHmacThenDecryptAsyncConstMeta,
        argValues: [ciphertext, mac, encKey, macKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateVerifyHmacThenDecryptAsyncConstMeta =>
      const TaskConstMeta(
        debugName: "verify_hmac_then_decrypt_async",
        argNames: ["ciphertext", "mac", "encKey", "macKey"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Sha1Hasher => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha1Hasher;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Sha1Hasher => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha1Hasher;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Sha256Hasher => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256Hasher;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Sha256Hasher => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256Hasher;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Sha256HmacHasher => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256HmacHasher;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Sha256HmacHasher => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256HmacHasher;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Sha512Hasher => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha512Hasher;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Sha512Hasher => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha512Hasher;

  @protected
  Sha1Hasher
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha1Hasher(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Sha1HasherImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Sha256Hasher
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256Hasher(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Sha256HasherImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Sha256HmacHasher
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256HmacHasher(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Sha256HmacHasherImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Sha512Hasher
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha512Hasher(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Sha512HasherImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Sha1Hasher
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha1Hasher(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Sha1HasherImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Sha256Hasher
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256Hasher(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Sha256HasherImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Sha256HmacHasher
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256HmacHasher(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Sha256HmacHasherImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Sha512Hasher
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha512Hasher(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Sha512HasherImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Sha1Hasher
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha1Hasher(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Sha1HasherImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Sha256Hasher
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256Hasher(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Sha256HasherImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Sha256HmacHasher
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256HmacHasher(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Sha256HmacHasherImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Sha512Hasher
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha512Hasher(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Sha512HasherImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  Sha256HmacHasher
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256HmacHasher(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256HmacHasher(
      raw,
    );
  }

  @protected
  (Uint8List, U8Array32)
  dco_decode_box_autoadd_record_list_prim_u_8_strict_u_8_array_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as (Uint8List, U8Array32);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_prim_u_8_strict).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<U8Array32> dco_decode_list_u_8_array_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_u_8_array_32).toList();
  }

  @protected
  List<U8Array64> dco_decode_list_u_8_array_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_u_8_array_64).toList();
  }

  @protected
  Sha256HmacHasher?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256HmacHasher(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256HmacHasher(
            raw,
          );
  }

  @protected
  (Uint8List, U8Array32)?
  dco_decode_opt_box_autoadd_record_list_prim_u_8_strict_u_8_array_32(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_record_list_prim_u_8_strict_u_8_array_32(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  (Uint8List, U8Array32) dco_decode_record_list_prim_u_8_strict_u_8_array_32(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_list_prim_u_8_strict(arr[0]),
      dco_decode_u_8_array_32(arr[1]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  U8Array16 dco_decode_u_8_array_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return U8Array16(dco_decode_list_prim_u_8_strict(raw));
  }

  @protected
  U8Array20 dco_decode_u_8_array_20(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return U8Array20(dco_decode_list_prim_u_8_strict(raw));
  }

  @protected
  U8Array28 dco_decode_u_8_array_28(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return U8Array28(dco_decode_list_prim_u_8_strict(raw));
  }

  @protected
  U8Array32 dco_decode_u_8_array_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return U8Array32(dco_decode_list_prim_u_8_strict(raw));
  }

  @protected
  U8Array48 dco_decode_u_8_array_48(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return U8Array48(dco_decode_list_prim_u_8_strict(raw));
  }

  @protected
  U8Array64 dco_decode_u_8_array_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return U8Array64(dco_decode_list_prim_u_8_strict(raw));
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  Sha1Hasher
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha1Hasher(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Sha1HasherImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Sha256Hasher
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256Hasher(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Sha256HasherImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Sha256HmacHasher
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256HmacHasher(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Sha256HmacHasherImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Sha512Hasher
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha512Hasher(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Sha512HasherImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Sha1Hasher
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha1Hasher(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Sha1HasherImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Sha256Hasher
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256Hasher(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Sha256HasherImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Sha256HmacHasher
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256HmacHasher(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Sha256HmacHasherImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Sha512Hasher
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha512Hasher(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Sha512HasherImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Sha1Hasher
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha1Hasher(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Sha1HasherImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Sha256Hasher
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256Hasher(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Sha256HasherImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Sha256HmacHasher
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256HmacHasher(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Sha256HmacHasherImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Sha512Hasher
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha512Hasher(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Sha512HasherImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  Sha256HmacHasher
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256HmacHasher(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256HmacHasher(
      deserializer,
    ));
  }

  @protected
  (Uint8List, U8Array32)
  sse_decode_box_autoadd_record_list_prim_u_8_strict_u_8_array_32(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_record_list_prim_u_8_strict_u_8_array_32(deserializer));
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint8List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<U8Array32> sse_decode_list_u_8_array_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <U8Array32>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_u_8_array_32(deserializer));
    }
    return ans_;
  }

  @protected
  List<U8Array64> sse_decode_list_u_8_array_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <U8Array64>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_u_8_array_64(deserializer));
    }
    return ans_;
  }

  @protected
  Sha256HmacHasher?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256HmacHasher(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256HmacHasher(
        deserializer,
      ));
    } else {
      return null;
    }
  }

  @protected
  (Uint8List, U8Array32)?
  sse_decode_opt_box_autoadd_record_list_prim_u_8_strict_u_8_array_32(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_record_list_prim_u_8_strict_u_8_array_32(
        deserializer,
      ));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (Uint8List, U8Array32) sse_decode_record_list_prim_u_8_strict_u_8_array_32(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_list_prim_u_8_strict(deserializer);
    var var_field1 = sse_decode_u_8_array_32(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  U8Array16 sse_decode_u_8_array_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return U8Array16(inner);
  }

  @protected
  U8Array20 sse_decode_u_8_array_20(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return U8Array20(inner);
  }

  @protected
  U8Array28 sse_decode_u_8_array_28(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return U8Array28(inner);
  }

  @protected
  U8Array32 sse_decode_u_8_array_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return U8Array32(inner);
  }

  @protected
  U8Array48 sse_decode_u_8_array_48(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return U8Array48(inner);
  }

  @protected
  U8Array64 sse_decode_u_8_array_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return U8Array64(inner);
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha1Hasher(
    Sha1Hasher self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Sha1HasherImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256Hasher(
    Sha256Hasher self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Sha256HasherImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256HmacHasher(
    Sha256HmacHasher self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Sha256HmacHasherImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha512Hasher(
    Sha512Hasher self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Sha512HasherImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha1Hasher(
    Sha1Hasher self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Sha1HasherImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256Hasher(
    Sha256Hasher self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Sha256HasherImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256HmacHasher(
    Sha256HmacHasher self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Sha256HmacHasherImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha512Hasher(
    Sha512Hasher self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Sha512HasherImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha1Hasher(
    Sha1Hasher self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Sha1HasherImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256Hasher(
    Sha256Hasher self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Sha256HasherImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256HmacHasher(
    Sha256HmacHasher self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Sha256HmacHasherImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha512Hasher(
    Sha512Hasher self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Sha512HasherImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256HmacHasher(
    Sha256HmacHasher self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256HmacHasher(
      self,
      serializer,
    );
  }

  @protected
  void sse_encode_box_autoadd_record_list_prim_u_8_strict_u_8_array_32(
    (Uint8List, U8Array32) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_record_list_prim_u_8_strict_u_8_array_32(self, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_u_8_array_32(
    List<U8Array32> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_u_8_array_32(item, serializer);
    }
  }

  @protected
  void sse_encode_list_u_8_array_64(
    List<U8Array64> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_u_8_array_64(item, serializer);
    }
  }

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256HmacHasher(
    Sha256HmacHasher? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256HmacHasher(
        self,
        serializer,
      );
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_record_list_prim_u_8_strict_u_8_array_32(
    (Uint8List, U8Array32)? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_record_list_prim_u_8_strict_u_8_array_32(
        self,
        serializer,
      );
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_record_list_prim_u_8_strict_u_8_array_32(
    (Uint8List, U8Array32) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.$1, serializer);
    sse_encode_u_8_array_32(self.$2, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_u_8_array_16(U8Array16 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.inner, serializer);
  }

  @protected
  void sse_encode_u_8_array_20(U8Array20 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.inner, serializer);
  }

  @protected
  void sse_encode_u_8_array_28(U8Array28 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.inner, serializer);
  }

  @protected
  void sse_encode_u_8_array_32(U8Array32 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.inner, serializer);
  }

  @protected
  void sse_encode_u_8_array_48(U8Array48 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.inner, serializer);
  }

  @protected
  void sse_encode_u_8_array_64(U8Array64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.inner, serializer);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class Sha1HasherImpl extends RustOpaque implements Sha1Hasher {
  // Not to be used by end users
  Sha1HasherImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  Sha1HasherImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Sha1Hasher,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Sha1Hasher,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_Sha1HasherPtr,
  );

  U8Array20 finalize() =>
      RustLib.instance.api.crateSha1HasherFinalize(that: this);

  void update({required List<int> data}) =>
      RustLib.instance.api.crateSha1HasherUpdate(that: this, data: data);
}

@sealed
class Sha256HasherImpl extends RustOpaque implements Sha256Hasher {
  // Not to be used by end users
  Sha256HasherImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  Sha256HasherImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Sha256Hasher,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Sha256Hasher,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_Sha256HasherPtr,
  );

  U8Array32 finalize() =>
      RustLib.instance.api.crateSha256HasherFinalize(that: this);

  void update({required List<int> data}) =>
      RustLib.instance.api.crateSha256HasherUpdate(that: this, data: data);
}

@sealed
class Sha256HmacHasherImpl extends RustOpaque implements Sha256HmacHasher {
  // Not to be used by end users
  Sha256HmacHasherImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  Sha256HmacHasherImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Sha256HmacHasher,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Sha256HmacHasher,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_Sha256HmacHasherPtr,
  );

  U8Array32 finalize() =>
      RustLib.instance.api.crateSha256HmacHasherFinalize(that: this);

  void update({required List<int> data}) =>
      RustLib.instance.api.crateSha256HmacHasherUpdate(that: this, data: data);
}

@sealed
class Sha512HasherImpl extends RustOpaque implements Sha512Hasher {
  // Not to be used by end users
  Sha512HasherImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  Sha512HasherImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Sha512Hasher,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Sha512Hasher,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_Sha512HasherPtr,
  );

  U8Array64 finalize() =>
      RustLib.instance.api.crateSha512HasherFinalize(that: this);

  void update({required List<int> data}) =>
      RustLib.instance.api.crateSha512HasherUpdate(that: this, data: data);
}
