// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 681677917;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  U8Array32 crateHmacSha256StateFinalize({required HmacSha256State that});

  HmacSha256State crateHmacSha256StateNew({required List<int> key});

  void crateHmacSha256StateUpdate({
    required HmacSha256State that,
    required List<int> data,
  });

  U8Array32 crateSha256HasherFinalize({required Sha256Hasher that});

  Sha256Hasher crateSha256HasherNew();

  void crateSha256HasherUpdate({
    required Sha256Hasher that,
    required List<int> data,
  });

  U8Array64 crateSha512HasherFinalize({required Sha512Hasher that});

  Sha512Hasher crateSha512HasherNew();

  void crateSha512HasherUpdate({
    required Sha512Hasher that,
    required List<int> data,
  });

  Future<Uint8List?> crateAes256DecryptAsync({
    required List<int> ciphertext,
    required List<int> key,
  });

  Uint8List? crateAes256DecryptSync({
    required List<int> ciphertext,
    required List<int> key,
  });

  Future<Uint8List?> crateAes256EncryptAsync({
    required List<int> plaintext,
    required List<int> key,
  });

  Uint8List? crateAes256EncryptSync({
    required List<int> plaintext,
    required List<int> key,
  });

  (Uint8List, U8Array32)? crateEncryptThenMacSync({
    required List<int> plaintext,
    required List<int> encKey,
    required List<int> macKey,
  });

  Uint8List? crateFromHexSync({required String hexString});

  BigInt crateHashSizeSync({required String algorithm});

  Uint8List? crateHashThenEncryptSync({
    required List<int> data,
    required List<int> key,
  });

  U8Array16 crateHmacMd5Sync({required List<int> key, required List<int> data});

  U8Array20 crateHmacSha1Sync({
    required List<int> key,
    required List<int> data,
  });

  U8Array28 crateHmacSha224Sync({
    required List<int> key,
    required List<int> data,
  });

  Future<U8Array32> crateHmacSha256Async({
    required List<int> key,
    required List<int> data,
  });

  List<U8Array32> crateHmacSha256BatchSync({
    required List<int> key,
    required List<Uint8List> messages,
  });

  U8Array32 crateHmacSha256Sync({
    required List<int> key,
    required List<int> data,
  });

  U8Array48 crateHmacSha384Sync({
    required List<int> key,
    required List<int> data,
  });

  Future<U8Array64> crateHmacSha512Async({
    required List<int> key,
    required List<int> data,
  });

  U8Array64 crateHmacSha512Sync({
    required List<int> key,
    required List<int> data,
  });

  Future<U8Array16> crateMd5Async({required List<int> data});

  U8Array16 crateMd5Sync({required List<int> data});

  Future<U8Array20> crateSha1Async({required List<int> data});

  U8Array20 crateSha1Sync({required List<int> data});

  U8Array28 crateSha224Sync({required List<int> data});

  Future<U8Array32> crateSha256Async({required List<int> data});

  List<U8Array32> crateSha256BatchSync({required List<Uint8List> inputs});

  U8Array32 crateSha256Sync({required List<int> data});

  Future<U8Array48> crateSha384Async({required List<int> data});

  U8Array48 crateSha384Sync({required List<int> data});

  U8Array28 crateSha512224Sync({required List<int> data});

  U8Array32 crateSha512256Sync({required List<int> data});

  Future<U8Array64> crateSha512Async({required List<int> data});

  U8Array64 crateSha512Sync({required List<int> data});

  String crateToHexSync({required List<int> bytes});

  Uint8List? crateVerifyThenDecryptSync({
    required List<int> ciphertext,
    required List<int> mac,
    required List<int> encKey,
    required List<int> macKey,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_HmacSha256State;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_HmacSha256State;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_HmacSha256StatePtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Sha256Hasher;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Sha256Hasher;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_Sha256HasherPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Sha512Hasher;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Sha512Hasher;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_Sha512HasherPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  U8Array32 crateHmacSha256StateFinalize({required HmacSha256State that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHmacSha256State(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateHmacSha256StateFinalizeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHmacSha256StateFinalizeConstMeta =>
      const TaskConstMeta(
        debugName: "HmacSha256State_finalize",
        argNames: ["that"],
      );

  @override
  HmacSha256State crateHmacSha256StateNew({required List<int> key}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHmacSha256State,
          decodeErrorData: null,
        ),
        constMeta: kCrateHmacSha256StateNewConstMeta,
        argValues: [key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHmacSha256StateNewConstMeta =>
      const TaskConstMeta(debugName: "HmacSha256State_new", argNames: ["key"]);

  @override
  void crateHmacSha256StateUpdate({
    required HmacSha256State that,
    required List<int> data,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHmacSha256State(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateHmacSha256StateUpdateConstMeta,
        argValues: [that, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHmacSha256StateUpdateConstMeta => const TaskConstMeta(
    debugName: "HmacSha256State_update",
    argNames: ["that", "data"],
  );

  @override
  U8Array32 crateSha256HasherFinalize({required Sha256Hasher that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256Hasher(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha256HasherFinalizeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha256HasherFinalizeConstMeta => const TaskConstMeta(
    debugName: "Sha256Hasher_finalize",
    argNames: ["that"],
  );

  @override
  Sha256Hasher crateSha256HasherNew() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256Hasher,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha256HasherNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha256HasherNewConstMeta =>
      const TaskConstMeta(debugName: "Sha256Hasher_new", argNames: []);

  @override
  void crateSha256HasherUpdate({
    required Sha256Hasher that,
    required List<int> data,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256Hasher(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha256HasherUpdateConstMeta,
        argValues: [that, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha256HasherUpdateConstMeta => const TaskConstMeta(
    debugName: "Sha256Hasher_update",
    argNames: ["that", "data"],
  );

  @override
  U8Array64 crateSha512HasherFinalize({required Sha512Hasher that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha512Hasher(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha512HasherFinalizeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha512HasherFinalizeConstMeta => const TaskConstMeta(
    debugName: "Sha512Hasher_finalize",
    argNames: ["that"],
  );

  @override
  Sha512Hasher crateSha512HasherNew() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha512Hasher,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha512HasherNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha512HasherNewConstMeta =>
      const TaskConstMeta(debugName: "Sha512Hasher_new", argNames: []);

  @override
  void crateSha512HasherUpdate({
    required Sha512Hasher that,
    required List<int> data,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha512Hasher(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha512HasherUpdateConstMeta,
        argValues: [that, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha512HasherUpdateConstMeta => const TaskConstMeta(
    debugName: "Sha512Hasher_update",
    argNames: ["that", "data"],
  );

  @override
  Future<Uint8List?> crateAes256DecryptAsync({
    required List<int> ciphertext,
    required List<int> key,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(ciphertext, serializer);
          sse_encode_list_prim_u_8_loose(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateAes256DecryptAsyncConstMeta,
        argValues: [ciphertext, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAes256DecryptAsyncConstMeta => const TaskConstMeta(
    debugName: "aes256_decrypt_async",
    argNames: ["ciphertext", "key"],
  );

  @override
  Uint8List? crateAes256DecryptSync({
    required List<int> ciphertext,
    required List<int> key,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(ciphertext, serializer);
          sse_encode_list_prim_u_8_loose(key, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateAes256DecryptSyncConstMeta,
        argValues: [ciphertext, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAes256DecryptSyncConstMeta => const TaskConstMeta(
    debugName: "aes256_decrypt_sync",
    argNames: ["ciphertext", "key"],
  );

  @override
  Future<Uint8List?> crateAes256EncryptAsync({
    required List<int> plaintext,
    required List<int> key,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(plaintext, serializer);
          sse_encode_list_prim_u_8_loose(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateAes256EncryptAsyncConstMeta,
        argValues: [plaintext, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAes256EncryptAsyncConstMeta => const TaskConstMeta(
    debugName: "aes256_encrypt_async",
    argNames: ["plaintext", "key"],
  );

  @override
  Uint8List? crateAes256EncryptSync({
    required List<int> plaintext,
    required List<int> key,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(plaintext, serializer);
          sse_encode_list_prim_u_8_loose(key, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateAes256EncryptSyncConstMeta,
        argValues: [plaintext, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAes256EncryptSyncConstMeta => const TaskConstMeta(
    debugName: "aes256_encrypt_sync",
    argNames: ["plaintext", "key"],
  );

  @override
  (Uint8List, U8Array32)? crateEncryptThenMacSync({
    required List<int> plaintext,
    required List<int> encKey,
    required List<int> macKey,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(plaintext, serializer);
          sse_encode_list_prim_u_8_loose(encKey, serializer);
          sse_encode_list_prim_u_8_loose(macKey, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_opt_box_autoadd_record_list_prim_u_8_strict_u_8_array_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateEncryptThenMacSyncConstMeta,
        argValues: [plaintext, encKey, macKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateEncryptThenMacSyncConstMeta => const TaskConstMeta(
    debugName: "encrypt_then_mac_sync",
    argNames: ["plaintext", "encKey", "macKey"],
  );

  @override
  Uint8List? crateFromHexSync({required String hexString}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hexString, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateFromHexSyncConstMeta,
        argValues: [hexString],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFromHexSyncConstMeta =>
      const TaskConstMeta(debugName: "from_hex_sync", argNames: ["hexString"]);

  @override
  BigInt crateHashSizeSync({required String algorithm}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(algorithm, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: null,
        ),
        constMeta: kCrateHashSizeSyncConstMeta,
        argValues: [algorithm],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHashSizeSyncConstMeta =>
      const TaskConstMeta(debugName: "hash_size_sync", argNames: ["algorithm"]);

  @override
  Uint8List? crateHashThenEncryptSync({
    required List<int> data,
    required List<int> key,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          sse_encode_list_prim_u_8_loose(key, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateHashThenEncryptSyncConstMeta,
        argValues: [data, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHashThenEncryptSyncConstMeta => const TaskConstMeta(
    debugName: "hash_then_encrypt_sync",
    argNames: ["data", "key"],
  );

  @override
  U8Array16 crateHmacMd5Sync({
    required List<int> key,
    required List<int> data,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_16,
          decodeErrorData: null,
        ),
        constMeta: kCrateHmacMd5SyncConstMeta,
        argValues: [key, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHmacMd5SyncConstMeta => const TaskConstMeta(
    debugName: "hmac_md5_sync",
    argNames: ["key", "data"],
  );

  @override
  U8Array20 crateHmacSha1Sync({
    required List<int> key,
    required List<int> data,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_20,
          decodeErrorData: null,
        ),
        constMeta: kCrateHmacSha1SyncConstMeta,
        argValues: [key, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHmacSha1SyncConstMeta => const TaskConstMeta(
    debugName: "hmac_sha1_sync",
    argNames: ["key", "data"],
  );

  @override
  U8Array28 crateHmacSha224Sync({
    required List<int> key,
    required List<int> data,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_28,
          decodeErrorData: null,
        ),
        constMeta: kCrateHmacSha224SyncConstMeta,
        argValues: [key, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHmacSha224SyncConstMeta => const TaskConstMeta(
    debugName: "hmac_sha224_sync",
    argNames: ["key", "data"],
  );

  @override
  Future<U8Array32> crateHmacSha256Async({
    required List<int> key,
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateHmacSha256AsyncConstMeta,
        argValues: [key, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHmacSha256AsyncConstMeta => const TaskConstMeta(
    debugName: "hmac_sha256_async",
    argNames: ["key", "data"],
  );

  @override
  List<U8Array32> crateHmacSha256BatchSync({
    required List<int> key,
    required List<Uint8List> messages,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_list_prim_u_8_strict(messages, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_u_8_array_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateHmacSha256BatchSyncConstMeta,
        argValues: [key, messages],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHmacSha256BatchSyncConstMeta => const TaskConstMeta(
    debugName: "hmac_sha256_batch_sync",
    argNames: ["key", "messages"],
  );

  @override
  U8Array32 crateHmacSha256Sync({
    required List<int> key,
    required List<int> data,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateHmacSha256SyncConstMeta,
        argValues: [key, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHmacSha256SyncConstMeta => const TaskConstMeta(
    debugName: "hmac_sha256_sync",
    argNames: ["key", "data"],
  );

  @override
  U8Array48 crateHmacSha384Sync({
    required List<int> key,
    required List<int> data,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_48,
          decodeErrorData: null,
        ),
        constMeta: kCrateHmacSha384SyncConstMeta,
        argValues: [key, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHmacSha384SyncConstMeta => const TaskConstMeta(
    debugName: "hmac_sha384_sync",
    argNames: ["key", "data"],
  );

  @override
  Future<U8Array64> crateHmacSha512Async({
    required List<int> key,
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateHmacSha512AsyncConstMeta,
        argValues: [key, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHmacSha512AsyncConstMeta => const TaskConstMeta(
    debugName: "hmac_sha512_async",
    argNames: ["key", "data"],
  );

  @override
  U8Array64 crateHmacSha512Sync({
    required List<int> key,
    required List<int> data,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateHmacSha512SyncConstMeta,
        argValues: [key, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateHmacSha512SyncConstMeta => const TaskConstMeta(
    debugName: "hmac_sha512_sync",
    argNames: ["key", "data"],
  );

  @override
  Future<U8Array16> crateMd5Async({required List<int> data}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_16,
          decodeErrorData: null,
        ),
        constMeta: kCrateMd5AsyncConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateMd5AsyncConstMeta =>
      const TaskConstMeta(debugName: "md5_async", argNames: ["data"]);

  @override
  U8Array16 crateMd5Sync({required List<int> data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_16,
          decodeErrorData: null,
        ),
        constMeta: kCrateMd5SyncConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateMd5SyncConstMeta =>
      const TaskConstMeta(debugName: "md5_sync", argNames: ["data"]);

  @override
  Future<U8Array20> crateSha1Async({required List<int> data}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_20,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha1AsyncConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha1AsyncConstMeta =>
      const TaskConstMeta(debugName: "sha1_async", argNames: ["data"]);

  @override
  U8Array20 crateSha1Sync({required List<int> data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_20,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha1SyncConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha1SyncConstMeta =>
      const TaskConstMeta(debugName: "sha1_sync", argNames: ["data"]);

  @override
  U8Array28 crateSha224Sync({required List<int> data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 31)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_28,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha224SyncConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha224SyncConstMeta =>
      const TaskConstMeta(debugName: "sha224_sync", argNames: ["data"]);

  @override
  Future<U8Array32> crateSha256Async({required List<int> data}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha256AsyncConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha256AsyncConstMeta =>
      const TaskConstMeta(debugName: "sha256_async", argNames: ["data"]);

  @override
  List<U8Array32> crateSha256BatchSync({required List<Uint8List> inputs}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_list_prim_u_8_strict(inputs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 33)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_u_8_array_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha256BatchSyncConstMeta,
        argValues: [inputs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha256BatchSyncConstMeta =>
      const TaskConstMeta(debugName: "sha256_batch_sync", argNames: ["inputs"]);

  @override
  U8Array32 crateSha256Sync({required List<int> data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 34)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha256SyncConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha256SyncConstMeta =>
      const TaskConstMeta(debugName: "sha256_sync", argNames: ["data"]);

  @override
  Future<U8Array48> crateSha384Async({required List<int> data}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_48,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha384AsyncConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha384AsyncConstMeta =>
      const TaskConstMeta(debugName: "sha384_async", argNames: ["data"]);

  @override
  U8Array48 crateSha384Sync({required List<int> data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 36)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_48,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha384SyncConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha384SyncConstMeta =>
      const TaskConstMeta(debugName: "sha384_sync", argNames: ["data"]);

  @override
  U8Array28 crateSha512224Sync({required List<int> data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 37)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_28,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha512224SyncConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha512224SyncConstMeta =>
      const TaskConstMeta(debugName: "sha512_224_sync", argNames: ["data"]);

  @override
  U8Array32 crateSha512256Sync({required List<int> data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 38)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha512256SyncConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha512256SyncConstMeta =>
      const TaskConstMeta(debugName: "sha512_256_sync", argNames: ["data"]);

  @override
  Future<U8Array64> crateSha512Async({required List<int> data}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 39,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha512AsyncConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha512AsyncConstMeta =>
      const TaskConstMeta(debugName: "sha512_async", argNames: ["data"]);

  @override
  U8Array64 crateSha512Sync({required List<int> data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 40)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateSha512SyncConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSha512SyncConstMeta =>
      const TaskConstMeta(debugName: "sha512_sync", argNames: ["data"]);

  @override
  String crateToHexSync({required List<int> bytes}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 41)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateToHexSyncConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateToHexSyncConstMeta =>
      const TaskConstMeta(debugName: "to_hex_sync", argNames: ["bytes"]);

  @override
  Uint8List? crateVerifyThenDecryptSync({
    required List<int> ciphertext,
    required List<int> mac,
    required List<int> encKey,
    required List<int> macKey,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(ciphertext, serializer);
          sse_encode_list_prim_u_8_loose(mac, serializer);
          sse_encode_list_prim_u_8_loose(encKey, serializer);
          sse_encode_list_prim_u_8_loose(macKey, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 42)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateVerifyThenDecryptSyncConstMeta,
        argValues: [ciphertext, mac, encKey, macKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateVerifyThenDecryptSyncConstMeta => const TaskConstMeta(
    debugName: "verify_then_decrypt_sync",
    argNames: ["ciphertext", "mac", "encKey", "macKey"],
  );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_HmacSha256State => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHmacSha256State;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_HmacSha256State => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHmacSha256State;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Sha256Hasher => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256Hasher;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Sha256Hasher => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256Hasher;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Sha512Hasher => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha512Hasher;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Sha512Hasher => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha512Hasher;

  @protected
  HmacSha256State
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHmacSha256State(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return HmacSha256StateImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Sha256Hasher
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256Hasher(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Sha256HasherImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Sha512Hasher
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha512Hasher(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Sha512HasherImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  HmacSha256State
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHmacSha256State(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return HmacSha256StateImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Sha256Hasher
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256Hasher(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Sha256HasherImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Sha512Hasher
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha512Hasher(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Sha512HasherImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  HmacSha256State
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHmacSha256State(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return HmacSha256StateImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Sha256Hasher
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256Hasher(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Sha256HasherImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Sha512Hasher
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha512Hasher(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Sha512HasherImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  (Uint8List, U8Array32)
  dco_decode_box_autoadd_record_list_prim_u_8_strict_u_8_array_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as (Uint8List, U8Array32);
  }

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_prim_u_8_strict).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<U8Array32> dco_decode_list_u_8_array_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_u_8_array_32).toList();
  }

  @protected
  (Uint8List, U8Array32)?
  dco_decode_opt_box_autoadd_record_list_prim_u_8_strict_u_8_array_32(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_record_list_prim_u_8_strict_u_8_array_32(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  (Uint8List, U8Array32) dco_decode_record_list_prim_u_8_strict_u_8_array_32(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_list_prim_u_8_strict(arr[0]),
      dco_decode_u_8_array_32(arr[1]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  U8Array16 dco_decode_u_8_array_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return U8Array16(dco_decode_list_prim_u_8_strict(raw));
  }

  @protected
  U8Array20 dco_decode_u_8_array_20(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return U8Array20(dco_decode_list_prim_u_8_strict(raw));
  }

  @protected
  U8Array28 dco_decode_u_8_array_28(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return U8Array28(dco_decode_list_prim_u_8_strict(raw));
  }

  @protected
  U8Array32 dco_decode_u_8_array_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return U8Array32(dco_decode_list_prim_u_8_strict(raw));
  }

  @protected
  U8Array48 dco_decode_u_8_array_48(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return U8Array48(dco_decode_list_prim_u_8_strict(raw));
  }

  @protected
  U8Array64 dco_decode_u_8_array_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return U8Array64(dco_decode_list_prim_u_8_strict(raw));
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  HmacSha256State
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHmacSha256State(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return HmacSha256StateImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Sha256Hasher
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256Hasher(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Sha256HasherImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Sha512Hasher
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha512Hasher(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Sha512HasherImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  HmacSha256State
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHmacSha256State(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return HmacSha256StateImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Sha256Hasher
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256Hasher(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Sha256HasherImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Sha512Hasher
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha512Hasher(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Sha512HasherImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  HmacSha256State
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHmacSha256State(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return HmacSha256StateImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Sha256Hasher
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256Hasher(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Sha256HasherImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Sha512Hasher
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha512Hasher(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Sha512HasherImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  (Uint8List, U8Array32)
  sse_decode_box_autoadd_record_list_prim_u_8_strict_u_8_array_32(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_record_list_prim_u_8_strict_u_8_array_32(deserializer));
  }

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint8List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<U8Array32> sse_decode_list_u_8_array_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <U8Array32>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_u_8_array_32(deserializer));
    }
    return ans_;
  }

  @protected
  (Uint8List, U8Array32)?
  sse_decode_opt_box_autoadd_record_list_prim_u_8_strict_u_8_array_32(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_record_list_prim_u_8_strict_u_8_array_32(
        deserializer,
      ));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (Uint8List, U8Array32) sse_decode_record_list_prim_u_8_strict_u_8_array_32(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_list_prim_u_8_strict(deserializer);
    var var_field1 = sse_decode_u_8_array_32(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  U8Array16 sse_decode_u_8_array_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return U8Array16(inner);
  }

  @protected
  U8Array20 sse_decode_u_8_array_20(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return U8Array20(inner);
  }

  @protected
  U8Array28 sse_decode_u_8_array_28(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return U8Array28(inner);
  }

  @protected
  U8Array32 sse_decode_u_8_array_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return U8Array32(inner);
  }

  @protected
  U8Array48 sse_decode_u_8_array_48(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return U8Array48(inner);
  }

  @protected
  U8Array64 sse_decode_u_8_array_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return U8Array64(inner);
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHmacSha256State(
    HmacSha256State self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as HmacSha256StateImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256Hasher(
    Sha256Hasher self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Sha256HasherImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha512Hasher(
    Sha512Hasher self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Sha512HasherImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHmacSha256State(
    HmacSha256State self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as HmacSha256StateImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256Hasher(
    Sha256Hasher self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Sha256HasherImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha512Hasher(
    Sha512Hasher self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Sha512HasherImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHmacSha256State(
    HmacSha256State self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as HmacSha256StateImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha256Hasher(
    Sha256Hasher self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Sha256HasherImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSha512Hasher(
    Sha512Hasher self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Sha512HasherImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_record_list_prim_u_8_strict_u_8_array_32(
    (Uint8List, U8Array32) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_record_list_prim_u_8_strict_u_8_array_32(self, serializer);
  }

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_u_8_array_32(
    List<U8Array32> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_u_8_array_32(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_record_list_prim_u_8_strict_u_8_array_32(
    (Uint8List, U8Array32)? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_record_list_prim_u_8_strict_u_8_array_32(
        self,
        serializer,
      );
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_record_list_prim_u_8_strict_u_8_array_32(
    (Uint8List, U8Array32) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.$1, serializer);
    sse_encode_u_8_array_32(self.$2, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_u_8_array_16(U8Array16 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.inner, serializer);
  }

  @protected
  void sse_encode_u_8_array_20(U8Array20 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.inner, serializer);
  }

  @protected
  void sse_encode_u_8_array_28(U8Array28 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.inner, serializer);
  }

  @protected
  void sse_encode_u_8_array_32(U8Array32 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.inner, serializer);
  }

  @protected
  void sse_encode_u_8_array_48(U8Array48 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.inner, serializer);
  }

  @protected
  void sse_encode_u_8_array_64(U8Array64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.inner, serializer);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class HmacSha256StateImpl extends RustOpaque implements HmacSha256State {
  // Not to be used by end users
  HmacSha256StateImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  HmacSha256StateImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_HmacSha256State,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_HmacSha256State,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_HmacSha256StatePtr,
  );

  U8Array32 finalize() =>
      RustLib.instance.api.crateHmacSha256StateFinalize(that: this);

  void update({required List<int> data}) =>
      RustLib.instance.api.crateHmacSha256StateUpdate(that: this, data: data);
}

@sealed
class Sha256HasherImpl extends RustOpaque implements Sha256Hasher {
  // Not to be used by end users
  Sha256HasherImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  Sha256HasherImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Sha256Hasher,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Sha256Hasher,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_Sha256HasherPtr,
  );

  U8Array32 finalize() =>
      RustLib.instance.api.crateSha256HasherFinalize(that: this);

  void update({required List<int> data}) =>
      RustLib.instance.api.crateSha256HasherUpdate(that: this, data: data);
}

@sealed
class Sha512HasherImpl extends RustOpaque implements Sha512Hasher {
  // Not to be used by end users
  Sha512HasherImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  Sha512HasherImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Sha512Hasher,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Sha512Hasher,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_Sha512HasherPtr,
  );

  U8Array64 finalize() =>
      RustLib.instance.api.crateSha512HasherFinalize(that: this);

  void update({required List<int> data}) =>
      RustLib.instance.api.crateSha512HasherUpdate(that: this, data: data);
}
